### ISSUE TITLE
nanoCUL 868

### ISSUE THREAD

**Issue by SaulGoodman1337** [pokerazor/openhab-binding-wmbus#1]
Hi,

i planing to use your add-on.
The Amber USB devices are very expensive. 
Is there much work to do here to implement a CUL? If i buy it, can you help me to implement this feature ?

Greetings Daniel

**Comment by pokerazor** [comment]
Hi!
Glad to hear you want to use it :)
I can't be sure, because sadly I don't own a CUL. Basically, the support has to be added to the underlying jMBus library. I guess, if you are familiar with the CUL and programming close to hardware (bytes and stuff), it should be doable without too much effort. I am happy to give you some guidance and suggestions but the coding would have to be done by you ;)

**Comment by SaulGoodman1337** [comment]
Hi,
now i used a another solution. I'm using fhem and a nanoCUL with WMBUS and build a bridge to get these values from fhem to openhab.
It is not a nice solution but it works.

Thanks for you attention.

btw:
[Here is a Screenshot from Basicui ](https://abload.de/img/screenshot2017-08-22ad7s25.png)

Greetings
Daniel Pondruff

**Comment by pokerazor** [comment]
Oh, what a pity :-(
But yes, it's currently the easier solution because it is working without additional programming.
Thanks for letting me know!
